name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  issue-labeled:
    permissions:
      issues: write  # for actions-cool/issues-helper to update issues
      pull-requests: write  # for actions-cool/issues-helper to update PRs
    runs-on: ubuntu-latest
    steps:
      - name: Need Reproduce
        if: github.event.label.name == 'ğŸ¤” Need Reproduce'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)ã€ [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository. Make sure to choose the correct version.

            ä½ å¥½ @${{ github.event.issue.user.login }}, æˆ‘ä»¬éœ€è¦ä½ æä¾›ä¸€ä¸ªåœ¨çº¿çš„é‡ç°å®ä¾‹ä»¥ä¾¿äºæˆ‘ä»¬å¸®ä½ æ’æŸ¥é—®é¢˜ã€‚ä½ å¯ä»¥é€šè¿‡ç‚¹å‡» [æ­¤å¤„ for vue2](https://codesandbox.io/s/2wpk21kzvr)ã€ [æ­¤å¤„ for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) åˆ›å»ºä¸€ä¸ª codesandbox æˆ–è€…æä¾›ä¸€ä¸ªæœ€å°åŒ–çš„ GitHub ä»“åº“ã€‚è¯·ç¡®ä¿é€‰æ‹©å‡†ç¡®çš„ç‰ˆæœ¬ã€‚
      
      - name: help wanted
        if: github.event.label.name == 'help wanted'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome to send us a Pull Request for it. Please send your Pull Request to proper branch, fill the Pull Request Template here, provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæˆ‘ä»¬å®Œå…¨åŒæ„ä½ çš„æè®®/åé¦ˆï¼Œæ¬¢è¿ç›´æ¥åœ¨æ­¤ä»“åº“åˆ›å»ºä¸€ä¸ª Pull Request æ¥è§£å†³è¿™ä¸ªé—®é¢˜ã€‚è¯·å°† Pull Request å‘åˆ°æ­£ç¡®çš„åˆ†æ”¯ï¼ŒåŠ¡å¿…å¡«å†™ Pull Request å†…çš„é¢„è®¾æ¨¡æ¿ï¼Œæä¾›æ”¹åŠ¨æ‰€éœ€ç›¸åº”çš„ changelogã€TypeScript å®šä¹‰ã€æµ‹è¯•ç”¨ä¾‹ã€æ–‡æ¡£ç­‰ï¼Œå¹¶ç¡®ä¿ CI é€šè¿‡ï¼Œæˆ‘ä»¬ä¼šå°½å¿«è¿›è¡Œ Reviewï¼Œæå‰æ„Ÿè°¢å’ŒæœŸå¾…æ‚¨çš„è´¡çŒ®ã€‚

      - name: Usage
        if: github.event.label.name == 'Usage'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment, close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, we use GitHub issues to trace bugs or discuss plans of Ant Design Vue. So, please don't ask usage questions here. You can try to open a new discussion in [antdv discussions](https://github.com/vueComponent/ant-design-vue/discussions), select `Q&A` to ask questions, also can ask questions on [Stack Overflow](http://stackoverflow.com/questions/) or [Segment Fault](https://segmentfault.com).

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼ŒAnt Design Vue Issue æ¿å—æ˜¯ç”¨äº bug åé¦ˆä¸éœ€æ±‚è®¨è®ºçš„åœ°æ–¹ã€‚è¯·å‹¿è¯¢é—®å¦‚ä½•ä½¿ç”¨çš„é—®é¢˜ï¼Œä½ å¯ä»¥è¯•ç€åœ¨ [antdv discussions](https://github.com/vueComponent/ant-design-vue/discussions) æ–°å¼€ä¸€ä¸ª discussionï¼Œé€‰æ‹© `Q&A` ç±»åˆ«è¿›è¡Œæé—®ï¼Œä¹Ÿå¯ä»¥åœ¨ [Stack Overflow](http://stackoverflow.com/questions/) æˆ–è€… [Segment Fault](https://segmentfault.com/) ä¸­æé—®ã€‚

      - name: 1.x
        if: github.event.label.name == '1.x'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.user.login }}. Current version (1.x) is off the maintenance period. We may not accept pull request or fix bug with it anymore. This topic will be auto closed.

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œå½“å‰ç‰ˆæœ¬ï¼ˆ1.xï¼‰å·²ç»è¿‡äº†ç»´æŠ¤æœŸã€‚æˆ‘ä»¬ä¸ä¼šå†æ¥å—å¯¹å…¶çš„ç›¸å…³ PR ä¸ issueã€‚å½“å‰ topic ä¼šè¢«è‡ªåŠ¨å…³é—­ã€‚

      - name: 2.x
        if: github.event.label.name == '2.x'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.user.login }}. Current version (2.x) is off the maintenance period. We may not accept pull request or fix bug with it anymore. This topic will be auto closed.

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œå½“å‰ç‰ˆæœ¬ï¼ˆ2.xï¼‰å·²ç»è¿‡äº†ç»´æŠ¤æœŸã€‚æˆ‘ä»¬ä¸ä¼šå†æ¥å—å¯¹å…¶çš„ç›¸å…³ PR ä¸ issueã€‚å½“å‰ topic ä¼šè¢«è‡ªåŠ¨å…³é—­ã€‚
  
