name: Add need reproduce

on:
  issues:
    types: [labeled]

jobs:
  add-need-reproduce:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ğŸ¤” Need Reproduce'
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide a online reproduction by forking this [link](https://codesandbox.io/s/2wpk21kzvr) or a minimal GitHub repository.Make sure to choose the correct version.
            
            ä½ å¥½ @${{ github.event.issue.user.login }}, æˆ‘ä»¬éœ€è¦ä½ æä¾›ä¸€ä¸ªåœ¨çº¿çš„é‡ç°å®ä¾‹ä»¥ä¾¿äºæˆ‘ä»¬å¸®ä½ æ’æŸ¥é—®é¢˜ã€‚ä½ å¯ä»¥é€šè¿‡ç‚¹å‡» [æ­¤å¤„](https://codesandbox.io/s/2wpk21kzvr) åˆ›å»ºä¸€ä¸ª codesandbox æˆ–è€…æä¾›ä¸€ä¸ªæœ€å°åŒ–çš„ GitHub ä»“åº“ã€‚è¯·ç¡®ä¿é€‰æ‹©å‡†ç¡®çš„ç‰ˆæœ¬ã€‚
